version: "3"
services:
  dailyturtles:
    image: ghcr.io/tekofx/dailyturtles:latest
    container_name: dailyturtles
    restart: unless-stopped
    env_file: .env

    volumes:
      - ./data:/bot/data